prt:
  offset: 9
  keys:
    0: High 8 bit
    1: Low 8 bit
    2: Vendor ID
    3: 0-6 bits = Version, bit 7 = floor limit state.
    4: Model
    5: Temperature format
    6: Switch Differential
    7: Frost Protection Mode
    8: Calibration - high 8 bit
    9: Calibration - low 8 bit
    10: Output delay
    11: Address
    12: Up down key limit
    13: Sensor Selection
    14: Optimum start
    15: Rate of change
    16: Program mode
    17: Frost protect temp
    18: Set room temp
    19: Floor max limit
    20: Floor max limit enable/disable
    21: On/off
    22: Key lock
    23: Run mode
    24: Holiday hours
    25: Holiday hours
    26: Temp hold mins
    27: Temp hold mins
    28: Remote air temp
    29: Remote air temp
    30: Floor temp
    31: Floor temp
    32: Built in air temp
    33: Built in air temp
    34: Error code
    35: Current state
    36: Week 1~7
    37: Hour
    38: Min
    39: Sec
    40: Weekday
    41: Weekday
    42: Weekday
    43: Weekday
    44: Weekday
    45: Weekday
    46: Weekday
    47: Weekday
    48: Weekday
    49: Weekday
    50: Weekday
    51: Weekday
    52: Weekend
    53: Weekend
    54: Weekend
    55: Weekend
    56: Weekend
    57: Weekend
    58: Weekend
    59: Weekend
    60: Weekend
    61: Weekend
    62: Weekend
    63: Weekend
  Responses:
prthw:
  offset: 9
  keys:
    0: High 8 bit
    1: Low 8 bit
    2: Vendor ID
    3: 0-6 bits = Version, bit 7 = floor limit state.
    4: Model
    5: Temperature format
    6: Switch Differential
    7: Frost Protection Mode
    8: Calibration - high 8 bit
    9: Calibration - low 8 bit
    10: Output delay
    11: Address
    12: Up down key limit
    13: Sensor Selection
    14: Optimum start
    15: Rate of change
    16: Program mode
    17: Frost protect temp
    18: Set room temp
    19: Floor max limit
    20: Floor max limit enable/disable
    21: On/off
    22: Key lock
    23: Run mode
    24: Holiday hours
    25: Holiday hours
    26: Temp hold mins
    27: Temp hold mins
    28: Remote air temp
    29: Remote air temp
    30: Floor temp
    31: Floor temp
    32: Built in air temp
    33: Built in air temp
    34: Error code
    35: Current state
    36: Current Hot water state
    37: Week 1~7
    38: Hour
    39: Min
    40: Sec
    41: Weekday Time 1 Hour
    42: Weekday Time 1 Min
    43: Weekday Time 1 Sec
    44: Weekday Time 2 Hour
    45: Weekday Time 2 Min
    46: Weekday Time 2 Sec
    47: Weekday Time 3 Hour
    48: Weekday Time 3 Min
    49: Weekday Time 3 Sec  
    50: Weekday Time 4 Hour 
    51: Weekday Time 4 Min
    52: Weekday Time 4 Sec    
    53: Weekend Time 1 Hour
    54: Weekend Time 1 Min
    55: Weekend Time 1 Sec
    56: Weekend Time 2 Hour
    57: Weekend Time 2 Min
    58: Weekend Time 2 Sec
    59: Weekend Time 3 Hour
    60: Weekend Time 3 Min
    61: Weekend Time 3 Sec
    62: Weekend Time 4 Hour
    63: Weekend Time 4 Min
    64: Weekend Time 4 Sec
    65: Weekday Time 1/On Hour
    66: Weekday Time 1/On Min
  Responses:    